"use client"

import Head from "next/head";
import { use, useEffect, useState } from "react";

class Soal {
    public pertanyaan: string = "";
    public pilihan: Array<{
        value: string,
        content: string
    }> = [];
    public jawaban: {
        value: string,
        content: string
    } = {
            value: "",
            content: ""
        };

    Soal(pertanyaan: string, pilihan: Array<{
        value: string,
        content: string
    }>, jawaban: {
        value: string,
        content: string
    }) {
        this.pertanyaan = pertanyaan;
        this.pilihan = pilihan;
        this.jawaban = jawaban;
    }
}

export default function pengerjaan() {
    const [questions, setQuestions] = useState<Soal[]>([]);

    const [answers, setAnswers] = useState<any[]>([]);

    useEffect(() => {
        const soalList: Soal[] = [];
        const rawSoal = JSON.parse(localStorage.getItem("soal") || "[]");
        rawSoal.forEach((element: any) => {
            const soalTemp = new Soal();
            soalTemp.pertanyaan = element.soal;
            soalTemp.pilihan = element.pilihan;
            soalTemp.jawaban = element.jawaban;
            soalList.push(soalTemp);
        });
        setQuestions(soalList)
        setAnswers(new Array(soalList.length));
    }, [])

    return (
        <div className="h-full bg-white">
            <Head>
                <title>Pengerjaan Soal</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="p-5">
                <div className="flex justify-center text-black">
                    <div className="w-4/5">
                        <div className="flex flex-col gap-5">
                            <div className="text-2xl font-bold mx-auto">
                                PENGERJAAN SOAL
                            </div>
                            <form>
                            {questions.map((question, i) => {
                                return (
                                    <div key={i} className="flex flex-col mt-3">
                                        <div>
                                            <span className="font-semibold text-lg">{i + 1}.</span> {question.pertanyaan}
                                        </div>
                                        <div className="flex flex-col gap-1">
                                            {question.pilihan.map((item, j) => {
                                                return (
                                                    <div key={j} className="flex gap-3">
                                                        <input type="radio" name={question.pertanyaan} value={item.value}
                                                            onChange={(e) => {
                                                                const temp = answers;
                                                                temp[i] = e.target.value;
                                                                setAnswers(temp);
                                                            }}
                                                        />
                                                        <label htmlFor={item.value}>{item.value}. {item.content}</label>
                                                    </div>
                                                )
                                            })}     
                                        </div>
                                    </div>
                                )
                            })}
                                <div className="flex justify-center">
                                    <button
                                        className="bg-yellow-500 text-white hover:bg-yellow-600 py-3 px-5 rounded-lg text-md font-semibold m-5 mt-10 w-1/2"
                                        onClick={(e) => {
                                            e.preventDefault();
                                            console.log(answers);
                                            if(answers.length === questions.length) {
                                                let score = 0;
                                                questions.forEach((question, i) => {
                                                    if(question.jawaban.value === answers[i]) {
                                                        score++;
                                                    }
                                                });
                                                alert(`Skor anda adalah ${score*10}`);
                                            }
                                        }}
                                    >
                                        Submit
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}
